name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get Deps
      run: go get -v -t -d ./scripts/mail-scripts/...
      
    - name: Build
      run: go build -v ./scripts/mail-scripts/...

#     - name: Test
#       run: go test -v ./...
